// <auto-generated />
using System;
using MamaFit.BusinessObjects.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MamaFit.BusinessObjects.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250521154247_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerify")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TokenId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ApplicationUserToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Branch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchManagerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.BranchMaternityDressDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaternityDressDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("MaternityDressDetailId");

                    b.ToTable("BranchMaternityDressDetails");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaternityDressDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaternityDressDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Component", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ComponentOption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComponentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentOptions");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.DesignOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DesignerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("UserId");

                    b.ToTable("DesignOrders");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Feedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("OrderItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("Rated")
                        .HasColumnType("real");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("MapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.ToTable("MaternityDresses");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressCustomization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomizationType")
                        .HasColumnType("int");

                    b.Property<string>("DesignerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DesignersId");

                    b.HasIndex("UserId");

                    b.ToTable("DressCustomizations");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaternityDressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaternityDressId");

                    b.ToTable("MaternityDressDetails");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressInspection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MaternityDressInspections");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressSelection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComponentOptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaternityDressCustomizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComponentOptionId");

                    b.HasIndex("MaternityDressCustomizationId");

                    b.ToTable("MaternityDressSelection");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Measurement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("ChestAround")
                        .HasColumnType("real");

                    b.Property<float>("Coat")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("Hip")
                        .HasColumnType("real");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MeasurementDiaryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Neck")
                        .HasColumnType("real");

                    b.Property<float>("ShoulderWidth")
                        .HasColumnType("real");

                    b.Property<float>("Stomach")
                        .HasColumnType("real");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementDiaryId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MeasurementDiary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPregnancy")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MeasurementDiaries");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OTP", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("OTPType")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OTP");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CanceledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("PanrentOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentOrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<float>("ShippingFee")
                        .HasColumnType("real");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<float>("SubTotalAmount")
                        .HasColumnType("real");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VoucherDiscountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarrantyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentOrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherDiscountId");

                    b.HasIndex("WarrantyHistoryId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("MaternityDressDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WarrantyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarrantyNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaternityDressDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OrderItemInspection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaternityDressInspectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaternityDressInspectionId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemInspections");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OrderItemProductionStage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCompelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductionStageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ProductionStageId");

                    b.ToTable("OrderItemProductionStages");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ProductionStage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRequire")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductionStage");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Style", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accumulated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gateway")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SepayId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("TransferAmount")
                        .HasColumnType("real");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.VoucherDiscount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VoucherDiscount");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.WarrantyHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarrantyRequestId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WarrantyRequestId");

                    b.ToTable("WarrantyHistories");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.WarrantyRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Fee")
                        .HasColumnType("real");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFactoryError")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalOrderItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarrantyOrderItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WarrantyRound")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OriginalOrderItemId");

                    b.HasIndex("WarrantyOrderItemId");

                    b.ToTable("WarrantyRequest");
                });

            modelBuilder.Entity("MaternityDressCustomizationOrderItem", b =>
                {
                    b.Property<string>("MaternityDressCustomizationsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderItemsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaternityDressCustomizationsId", "OrderItemsId");

                    b.HasIndex("OrderItemsId");

                    b.ToTable("MaternityDressCustomizationOrderItem");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ApplicationUser", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUserToken", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId");

                    b.Navigation("Role");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Appointment", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Branch", "Branch")
                        .WithMany("Appointments")
                        .HasForeignKey("BranchId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Branch", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "BranchManager")
                        .WithMany()
                        .HasForeignKey("BranchManagerId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("BranchManager");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.BranchMaternityDressDetail", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Branch", "Branch")
                        .WithMany("BranchMaternityDressDetail")
                        .HasForeignKey("BranchId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.MaternityDressDetail", "MaternityDressDetail")
                        .WithMany("BranchMaternityDressDetail")
                        .HasForeignKey("MaternityDressDetailId");

                    b.Navigation("Branch");

                    b.Navigation("MaternityDressDetail");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.CartItem", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.MaternityDressDetail", "MaternityDressDetail")
                        .WithMany("CartItems")
                        .HasForeignKey("MaternityDressDetailId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MaternityDressDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Component", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Style", "Style")
                        .WithMany("Components")
                        .HasForeignKey("StyleId");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ComponentOption", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Component", "Component")
                        .WithMany("Option")
                        .HasForeignKey("ComponentId");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.DesignOrder", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "Designer")
                        .WithMany()
                        .HasForeignKey("DesignerId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.OrderItem", null)
                        .WithMany("DesignOrders")
                        .HasForeignKey("OrderItemId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("DesignOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Designer");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Feedback", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.OrderItem", "OrderItem")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OrderItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Location", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("Location")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDress", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleId");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressCustomization", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "Designers")
                        .WithMany()
                        .HasForeignKey("DesignersId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "Users")
                        .WithMany("DressCustomizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Designers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressDetail", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.MaternityDress", "MaternityDress")
                        .WithMany("Details")
                        .HasForeignKey("MaternityDressId");

                    b.Navigation("MaternityDress");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressSelection", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ComponentOption", "ComponentOption")
                        .WithMany("MaternityDressSelections")
                        .HasForeignKey("ComponentOptionId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.MaternityDressCustomization", "MaternityDressCustomization")
                        .WithMany("MaternityDressSelections")
                        .HasForeignKey("MaternityDressCustomizationId");

                    b.Navigation("ComponentOption");

                    b.Navigation("MaternityDressCustomization");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Measurement", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.MeasurementDiary", null)
                        .WithMany("Measurements")
                        .HasForeignKey("MeasurementDiaryId");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MeasurementDiary", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("MeasurementDiaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Notification", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OTP", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("OTPs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Order", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Order", "ParentOrder")
                        .WithMany()
                        .HasForeignKey("ParentOrderId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MamaFit.BusinessObjects.Entity.VoucherDiscount", "VoucherDiscount")
                        .WithMany()
                        .HasForeignKey("VoucherDiscountId");

                    b.HasOne("MamaFit.BusinessObjects.Entity.WarrantyHistory", "WarrantyHistory")
                        .WithMany()
                        .HasForeignKey("WarrantyHistoryId");

                    b.Navigation("ParentOrder");

                    b.Navigation("User");

                    b.Navigation("VoucherDiscount");

                    b.Navigation("WarrantyHistory");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OrderItem", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.MaternityDressDetail", "MaternityDressDetail")
                        .WithMany("OrderItems")
                        .HasForeignKey("MaternityDressDetailId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MamaFit.BusinessObjects.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MaternityDressDetail");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OrderItemInspection", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.MaternityDressInspection", "MaternityDressInspection")
                        .WithMany("ItemInspections")
                        .HasForeignKey("MaternityDressInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamaFit.BusinessObjects.Entity.OrderItem", "OrderItem")
                        .WithMany("OrderItemInspections")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MaternityDressInspection");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OrderItemProductionStage", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.OrderItem", "OrderItem")
                        .WithMany("OrderItemProductionStages")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MamaFit.BusinessObjects.Entity.ProductionStage", "ProductionStage")
                        .WithMany("OrderItemProductionStages")
                        .HasForeignKey("ProductionStageId");

                    b.Navigation("OrderItem");

                    b.Navigation("ProductionStage");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Style", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Category", "Category")
                        .WithMany("Styles")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Transaction", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.VoucherDiscount", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.ApplicationUser", "User")
                        .WithMany("VoucherDiscounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.WarrantyHistory", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.WarrantyRequest", "WarrantyRequest")
                        .WithMany("WarrantyHistories")
                        .HasForeignKey("WarrantyRequestId");

                    b.Navigation("WarrantyRequest");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.WarrantyRequest", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.OrderItem", "OriginalOrderItem")
                        .WithMany("WarrantyRequests")
                        .HasForeignKey("OriginalOrderItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MamaFit.BusinessObjects.Entity.OrderItem", "WarrantyOrderItem")
                        .WithMany()
                        .HasForeignKey("WarrantyOrderItemId");

                    b.Navigation("OriginalOrderItem");

                    b.Navigation("WarrantyOrderItem");
                });

            modelBuilder.Entity("MaternityDressCustomizationOrderItem", b =>
                {
                    b.HasOne("MamaFit.BusinessObjects.Entity.MaternityDressCustomization", null)
                        .WithMany()
                        .HasForeignKey("MaternityDressCustomizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamaFit.BusinessObjects.Entity.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CartItems");

                    b.Navigation("DesignOrders");

                    b.Navigation("DressCustomizations");

                    b.Navigation("Feedbacks");

                    b.Navigation("Location");

                    b.Navigation("MeasurementDiaries");

                    b.Navigation("Notifications");

                    b.Navigation("OTPs");

                    b.Navigation("Orders");

                    b.Navigation("VoucherDiscounts");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Branch", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BranchMaternityDressDetail");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Category", b =>
                {
                    b.Navigation("Styles");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Component", b =>
                {
                    b.Navigation("Option");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ComponentOption", b =>
                {
                    b.Navigation("MaternityDressSelections");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDress", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressCustomization", b =>
                {
                    b.Navigation("MaternityDressSelections");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressDetail", b =>
                {
                    b.Navigation("BranchMaternityDressDetail");

                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MaternityDressInspection", b =>
                {
                    b.Navigation("ItemInspections");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.MeasurementDiary", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.OrderItem", b =>
                {
                    b.Navigation("DesignOrders");

                    b.Navigation("Feedbacks");

                    b.Navigation("OrderItemInspections");

                    b.Navigation("OrderItemProductionStages");

                    b.Navigation("WarrantyRequests");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.ProductionStage", b =>
                {
                    b.Navigation("OrderItemProductionStages");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.Style", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("MamaFit.BusinessObjects.Entity.WarrantyRequest", b =>
                {
                    b.Navigation("WarrantyHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
